import React, { ReactElement } from 'react';

import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: ReactElement;
}
export const Layout = ({ children }: Props): ReactElement => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Fake Shop</h1>
      </header>
      <main className={inter.className}>{children}</main>
      <footer>@copyright</footer>
    </>
  );
};
